### ISSUE TITLE
cutefish-terminal does not open/run

### ISSUE THREAD

**Issue by maybeageek** [cutefishos/terminal#1]
Hi all,
first: Thanks for the very good work on this!

I built the terminal according to the instructions, but it does not run.
I can see it in the launcher of cutefish DE; but it won't start.

When I start it from another terminal I get the following:

```
$ cutefish-terminal 
Qt: Session management error: networkIdsList argument is NULL
QQmlApplicationEngine failed to load component
qrc:/qml/main.qml:144:25: FishUI.RoundImageButton is not a type
```

Is this supposed to run yet or not finished yet?

**Comment by reionwong** [comment]
Need to compile and install the latest [https://github.com/cutefishos/fishui](https://github.com/cutefishos/fishui)

**Comment by maybeageek** [comment]
perfect, now its working. Thanks a bunch.

I guess this will be part of release 0.4 then. Thanks again
